### ISSUE TITLE
echo when playing in same area

### ISSUE THREAD

**Issue by virusmarathe** [BananaHemic/Mumble-Unity#14]
For our case, we have multiple people in the same room talking to each other. The main problem we are facing is that the mics are picking up other people's audio and playing it back so they hear themselves echo. The main thing I was using to deal with this was the mic threshold value, trying to find the sweetspot to get rid of outside audio while still picking up the main person's mic. While this works, it obviously has some edge cases where someone can be yelling far away or the person who has the mic talks too quietly.

I was wondering, is there another setting you know of that can help with this issue, or is threshold the way to go? If not, you can go ahead and close this, was just checking to see if I wasn't missing anything.

**Comment by Bananahavoc** [comment]
That sounds like a really tough issue to solve. The two options I see are:

1. Using a beamforming mic to eliminate other speakers/noise sources before the audio hits Unity
2. Instead of using amplitude, use the Signal-To-Noise ratio to filter out other speakers. The standard Mumble Client has this feature, so you might have luck looking at how they chose to implement it.

Best of luck!
