### ISSUE TITLE
CPU usage 

### ISSUE THREAD

**Issue by micz84** [BananaHemic/Mumble-Unity#7]
I have been testing this client and I have noticed that it uses a lot of CPU. It uses 15% of i7 7700k.

**Comment by Bananahavoc** [comment]
You were right, there was a very large CPU usage when streaming audio. It turns out this was because the encoding thread failed to terminate or sleep when necessary. I fixed this in 5bb86edb9652e857661e8c81cbeeb02ba16ac06a

Thanks for taking the time to let me know about this issue. If you still get poor performance, feel free to reopen.
